import { useRef } from "react";
import { Printer, Download } from "lucide-react";
import { formatCurrency } from "../../utils/formatters";

function ScorePill({ children, tone = "slate" }) {
 const styles = {
 slate: "border-slate-200 bg-slate-50 text-slate-700 ",
 emerald: "border-emerald-200 bg-emerald-50 text-emerald-700 ",
 amber: "border-amber-200 bg-amber-50 text-amber-700 ",
 };
 return <span className={`rounded-full border px-3 py-1.5 text-xs font-semibold ${styles[tone]}`}>{children}</span>;
}

export default function ComparisonTable({ policies, selectedIds, onToggle }) {
 const selected = policies.filter((policy) => selectedIds.includes(policy.id)).slice(0, 3);
 const tableRef = useRef(null);

 const handlePrintPDF = () => {
 const printContents = tableRef.current;
 if (!printContents) return;

 const printWindow = window.open("", "_blank");
 printWindow.document.write(`
 <html>
 <head>
 <title>InsureAI — Policy Comparison</title>
 <style>
 body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 32px; color: #1e293b; }
 h1 { font-size: 22px; margin-bottom: 4px; }
 .subtitle { font-size: 13px; color: #64748b; margin-bottom: 24px; }
 table { width: 100%; border-collapse: collapse; font-size: 13px; }
 th { background: #f8fafc; padding: 12px 16px; text-align: left; border-bottom: 2px solid #e2e8f0; font-weight: 600; color: #334155; }
 td { padding: 10px 16px; border-bottom: 1px solid #f1f5f9; color: #475569; }
 tr:nth-child(even) td { background: #fafbfc; }
 .footer { margin-top: 32px; font-size: 11px; color: #94a3b8; text-align: center; }
 </style>
 </head>
 <body>
 <h1>Policy Comparison Report</h1>
 <p class="subtitle">Generated by InsureAI on ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}</p>
 ${printContents.outerHTML}
 <p class="footer">This is a system-generated comparison for informational purposes only. Please verify details with the insurer before purchasing.</p>
 </body>
 </html>
 `);
 printWindow.document.close();
 printWindow.focus();
 setTimeout(() => {
 printWindow.print();
 printWindow.close();
 }, 300);
 };

 return (
 <div className="rounded-[28px] border border-slate-200 bg-white/90 p-6 shadow-sm ">
 <div className="flex items-center justify-between gap-4">
 <div>
 <h3 className="text-lg font-bold text-slate-900 ">Compare Policies</h3>
 <p className="text-sm text-slate-500 ">Select 2 to 3 plans to compare side-by-side.</p>
 </div>
 <div className="flex items-center gap-2">
 <ScorePill tone="amber">Selected: {selected.length}/3</ScorePill>
 {selected.length >= 2 && (
 <button
 type="button"
 onClick={handlePrintPDF}
 className="flex items-center gap-1.5 rounded-full border border-primary-200 bg-primary-50 px-3 py-1.5 text-xs font-semibold text-primary-700 transition hover:bg-primary-100 "
 >
 <Download className="h-3.5 w-3.5" /> Export PDF
 </button>
 )}
 </div>
 </div>

 <div className="mt-4 flex flex-wrap gap-2">
 {policies.slice(0, 5).map((policy) => {
 const active = selectedIds.includes(policy.id);
 return (
 <button
 key={policy.id}
 type="button"
 onClick={() => onToggle(policy.id)}
 className={`rounded-full border px-3 py-2 text-xs font-semibold ${
 active
 ? "border-primary-500 bg-primary-50 text-primary-700 "
 : "border-slate-200 bg-slate-50 text-slate-600 "
 }`}
 >
 {policy.name}
 </button>
 );
 })}
 </div>

 {selected.length >= 2 ? (
 <div className="mt-5 overflow-x-auto">
 <table ref={tableRef} className="min-w-full text-left text-sm">
 <thead>
 <tr className="border-b-2 border-slate-200 ">
 <th className="sticky left-0 z-10 bg-white pb-3 pr-4 text-slate-500 ">Metric</th>
 {selected.map((policy) => (
 <th key={policy.id} className="pb-3 pr-6 text-slate-900 ">{policy.name}</th>
 ))}
 </tr>
 </thead>
 <tbody>
 {[
 ["Company", (policy) => policy.company],
 ["Coverage", (policy) => formatCurrency(policy.coverage || 0)],
 ["Premium / year", (policy) => formatCurrency(policy.yearlyPremium || 0)],
 ["Premium / month", (policy) => formatCurrency(policy.monthlyPremium || 0)],
 ["Match Score", (policy) => `${policy.matchScore}%`],
 ["Confidence", (policy) => `${policy.confidenceScore}%`],
 ].map(([label, valueFn]) => (
 <tr key={label} className="border-b border-slate-100 hover:bg-slate-50/50 transition-colors">
 <td className="sticky left-0 z-10 bg-white py-3 pr-4 font-medium text-slate-500 ">{label}</td>
 {selected.map((policy) => (
 <td key={`${policy.id}-${label}`} className="py-3 pr-6 text-slate-900 ">{valueFn(policy)}</td>
 ))}
 </tr>
 ))}
 </tbody>
 </table>
 </div>
 ) : (
 <div className="mt-5 rounded-2xl border border-dashed border-slate-200 bg-slate-50 px-4 py-5 text-sm text-slate-500 ">
 Pick at least two recommendations to unlock comparison.
 </div>
 )}
 </div>
 );
}
