export const ERROR_CODES = {
  VALIDATION_FAILED: "VALIDATION_FAILED",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  CONFLICT: "CONFLICT",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PROVIDER_CONFIG_MISSING: "PROVIDER_CONFIG_MISSING",
  FRAUD_REVIEW_REQUIRED: "FRAUD_REVIEW_REQUIRED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
};

